config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#news'

  get '/logout',  to: 'user_sessions#destroy', as: :logout
  get '/login',   to: 'user_sessions#new',     as: :login
  get '/about',   to: 'pages#about',           as: :about
  get '/news',    to: 'pages#news',            as: :news
  get '/supporters',   to: 'pages#supporters', as: :supporters
  get '/guidelines',   to: 'pages#guidelines', as: :guidelines
  get '/tips',    to: 'pages#tips',            as: :tips
  get '/contact', to: 'pages#contact',         as: :contact
  get '/robots',  to: 'pages#robots',          as: :robots
  get '/privacy_policy', to: 'pages#privacy_policy', as: :privacy_policy
  get '/terms_of_service', to: 'pages#terms_of_service', as: :terms_of_service

  get '/activate/:id',              to: 'activations#create', as: :activation
  get '/register/:activation_code', to: 'activations#new',    as: :registration
  get 'tags/:tag',                  to: 'presentations#index', as: :tag

  # Provide redirects for legacy conference routes
  get "/conferences",         to: redirect(QueryRedirector.new("/events"))
  get 'conferences/upcoming', to: redirect('/events/upcoming')
  get "/conferences/chart",   to: redirect(QueryRedirector.new("/events/chart"))
  get 'conferences/:slug',    to: redirect('/events/%{slug}')

  namespace :api do
    resources :presentations
    resources :publications
    resources :speakers
  end

  resource  :account
  resources :events do
    collection do
      get :cities_count_by    # the chart data endpoint - returns JSON
      get :chart              # queries the data, renders the chart
      get :upcoming           # for the landing page
    end
    resources :supplements, except: [:index] do
      member do
        get :download
      end
    end
  end
  resources :event_users, only: [:index, :create, :destroy]
  resources :documents do
    member do
      get :download
    end
  end
  resources :languages
  resources :passages
  resources :presentation_publications, only: [:create, :destroy]
  resources :presentation_speakers, only: [:create, :destroy]
  resources :presentations do
    member do
      get :manage_speakers, :manage_publications, :manage_related, :download_handout
    end
    collection do
      get :chart                     # queries the data and pushes it to the chart in an array
      get :tags
    end
  end
  resources :publications do
    collection do
      get :chart                     # queries the data and pushes it to the chart in an array
      get :latest                    # for the landing page
    end
  end
  resources :publishers, except: [:new, :show]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :organizers
  resources :relations, only: [:new, :create, :destroy]
  resources :settings, only: [:index, :show, :edit, :update]
  resources :speakers do
    collection do
      get :presentations_count_by    # the chart data endpoint - returns JSON
      get :chart                     # queries the data and pushes it to the chart in an array
    end
  end
  resources :supplements, only: [:index]    # the supplements dashboard, outside the event context
  resources :users do
    member do
      patch :approve
    end
    collection do
      get   :events
      get   :names
      get   :summary
      get   :supporters
      get   :systat
    end
  end
  resources :user_presentations, only: [:index, :create, :update, :destroy] do
    collection do
      get :most_watched
      get :most_anticipated
      get :notifications
    end
  end
  resources :user_sessions, only: [:new, :create, :destroy]
end

app/models/supplement.rb
class Supplement < ApplicationRecord

  mount_uploader :attachment, DocumentUploader

  belongs_to :conference
  belongs_to :creator,    class_name: "User"

  validates :name, :description, :conference_id, presence: true
  validates :url, http_url: true, allow_blank: true

  validate :url_or_attachment

  def url_or_attachment
    errors.add(:url, 'Either URL or attachment must be provided') if url.blank? && attachment.blank?
    errors.add(:url, 'Specify either URL or attachment, but not both') if url.present? && attachment.present?
  end

  # Gives the description with any HTML tags stripped out
  def clean_description
    ActionView::Base.full_sanitizer.sanitize(description)
  end

  def clean_editors_notes
    ActionView::Base.full_sanitizer.sanitize(editors_notes)
  end

  # For attachments, it returns the name with '.pdf' appended, otherwise the plain name.
  def contextual_name
    url.present? ? name : name + '.pdf'
  end

  def event_name
    conference&.name
  end

  def event_date
    if conference.start_date.present?
      ApplicationController.helpers.pretty_date conference.start_date, style: :long
    else
      'n/a'
    end
  end

  # For attachments, it returns the download URL, otherwise the url attribute.
  def contextual_url
    url.present? ? url : Rails.application.routes.url_helpers.download_event_supplement_url(conference_id, id)
  end

  # Hash of human-friendly CSV column names and the methods that get the data
  TITLES_AND_METHODS = {
    'Name'          => :contextual_name,
    'Event'         => :event_name,
    'Event Date'    => :event_date,          # So the sheet can be easily sorted into events/index order
    'URL'           => :contextual_url,
    'Description'   => :clean_description,
    'Editors Notes' => :clean_editors_notes
  }

  # DocumentWorker uses this to get the header for generated CSV output
  def self.csv_header
    TITLES_AND_METHODS.keys
  end

  def csv_row
    TITLES_AND_METHODS.values.map{|v| self.send(v)}
  end
end

app/controllers/supplements_controller.rb
class SupplementsController < ApplicationController

  include StickyNavigation

  before_action :get_event,      except: [:index, :download]
  before_action :get_supplement, except: [:index, :new, :create]
  before_action :check_nav_params, only: [:index]

  before_action :require_user,     only: [:index]

  # This drives the supplement dashboard, outside the context of specific events
  def index
    @supplements = Supplement.includes(:conference).order(params_to_sql('>conferences.start_date'))

    @supplements = @supplements.page(param_context(:page)).per(param_context(:per))
    repaginate_if_needed(@supplements)
  end

  def show
  end

  def edit
  end

  def new
    @supplement = Supplement.new
  end

  def create
    @supplement = Supplement.new supplement_params
    @supplement.description.strip!
    @supplement.creator_id = current_user.id
    @supplement.conference = @event
    if @supplement.save
      redirect_to event_path(@event)
    else
      flash.now[:error] = "Your supplement could not be saved: #{ @supplement.errors.full_messages.join(", ") }"
      logger.error "Supplement save failed: #{ @supplement.errors.full_messages.join(", ") }"
      render 'new'
    end
  end

  def update
    if @supplement.update_attributes supplement_params
      redirect_to event_path(@event)
    else
      flash.now[:error] = "Your changes could not be saved: #{ @supplement.errors.full_messages.join(', ') }"
      logger.error "Supplement update failed: #{ @supplement.errors.full_messages.join(', ') }"
      render 'edit'
    end
  end

  def download
    send_data @supplement.attachment.read, type: @supplement.content_type, disposition: 'inline', filename: @supplement.name
  end

  def destroy
    event = @supplement.conference
    if can?(:destroy, @supplement)
      @supplement.destroy
    else
      flash[:notice] = "You don't have rights to delete that supplemental info."
    end

    redirect_to event_path(@event)
  end

  private

  def get_supplement
    @supplement = Supplement.find params[:id]
  end

  def get_event
    if @supplement.present?
      @event = @supplement.conference
    else
      @event = Conference.friendly.find params[:event_id]
    end
  end

  def supplement_params
    params.require(:supplement).permit(:name, :description, :url, :attachment, :conference_id, :editors_notes)
  end
end

app/helpers/supplements_helper.rb
module SupplementsHelper

  # Options:  :link_classes,
  def linked_icon_for_supplement(supplement, options={})
    if supplement.url.present?
      link_to icon('far', 'external-link-alt', class: 'fa-fw'), supplement.url, target: '_blank', title: supplement.name, class: options[:link_classes]
    else
      icon_name = supplement.content_type.include?('pdf') ? 'file-pdf' : 'file-image'
      link_to icon('far', icon_name, class: 'fa-fw'), download_event_supplement_path(supplement.conference, supplement), target: '_blank', title: supplement.name, class: options[:link_classes]
    end
  end

end

app/views/supplements/_control_bar.html.haml
-# This puts the navbar outside the content div so it can span the page
- content_for :body do
  %nav.navbar.navbar-expand-lg.navbar-dark
    .container
      %ul.navbar-nav.mr-auto
        -# This should only show up for the index action in the Supplements Dashboard
        - if action_name == 'index'
          %li.nav-item{ class: 'mr-1 d-inline-block d-lg-list-item' }
            -# This gets a nav reset because Documents and Supplements subtabs are run by different controllers
            = link_to "Documents", documents_path(nav: 'reset'), class: 'nav-link', title: 'Manage System Summary Documents'
          %li.nav-item{ class: 'active mr-1 d-inline-block d-lg-list-item' }
            = link_to "Supplements",  "#", class: 'nav-link', title: 'Supplemental Documents and Links'

      -# action-specific buttons - these should never show up in index
      - if action_name == 'show'
        - if can?(:destroy, @supplement) && @supplement.conference.blank?
          = link_to icon('far', 'trash-alt', '', class: 'fa-fw'), event_supplement_path(@supplement.conference_id, @supplement), :method => :delete, :class => "btn btn-sm btn-danger ml-3", :data => { :confirm => 'Are you sure?' }, :post => true
        - if can? :edit, @supplement
          = link_to "Edit", edit_event_supplement_path(@supplement.conference_id, @supplement), :class => "btn btn-sm btn-primary"
        = link_to "Done", deduce_done_path, :class => "btn btn-sm btn-secondary ml-3"

      - elsif action_name == 'edit' || action_name == 'update'
        = link_to "Save", "#", class: 'btn btn-sm btn-primary mr-3', onclick: "$('form.edit_supplement').submit()"
        = link_to "Cancel", event_path(params[:event_id]), :class => "btn btn-sm btn-secondary ml-3"
      - elsif action_name == 'new' || action_name == 'create'
        = link_to "Create", "#", class: 'btn btn-sm btn-primary mr-3', onclick: "$('form.new_supplement').submit()"
        = link_to "Cancel",  event_path(params[:event_id]), :class => "btn btn-sm btn-secondary ml-3"

app/views/supplements/_form_fields.html.haml
= f.input :name, label: 'Name', hint: 'Used as name of downloads, hovertip of URLs'
= f.label :description
= f.trix_editor :description

-# supplements are either about a URL to info, or an attached file, but not both at the same time
- if action_name == 'new'
  %br
  %p Enter a URL or attach a PDF - but not both
- unless @supplement.attachment.present?
  = f.input :url
- unless @supplement.url.present?
  = f.input :attachment, label: @supplement.attachment.present? ? 'Change attachment' : 'Add attachment'

= f.label :editors_notes, "Editor's Notes"
= f.trix_editor :editors_notes

app/views/supplements/_header.html.haml
.row.mb-2
  .col= sorting_header 'Event',      :supplements_path, 'conferences.name'
  .col= sorting_header 'Event Date', :supplements_path, 'conferences.start_date'
  .col.col-sm-6
    %strong Name
  .col-sm-1
    %strong Info
  .col-sm-1
    %strong Get

app/views/supplements/_supplement.html.haml
.row.mb-2
  .col= link_to(truncate(supplement.conference.name, length: 40, separator: ' '), event_path(supplement.conference))
  .col= unbreakable pretty_date(supplement.conference.start_date, style: :pretty)
  .col.col-sm-6= truncate(supplement.name, length: 40)
  .col-sm-1
    = link_to icon('far', 'eye'), event_supplement_path(supplement.conference, supplement)
  .col-sm-1
    = linked_icon_for_supplement(supplement)

app/views/supplements/edit.html.haml
- title 'Edit Supplemental Info'

= render partial: 'control_bar'

.row
  .col-md-12
    %h3
      Edit supplemental info for
      = @event.name
    = simple_form_for [@event, @supplement], url: event_supplement_path(@event, @supplement), :html => {:autocomplete => "off"}  do |f|
      = render :partial => "form_fields", :locals => {:f => f}
      = save_or_cancel f, params[:conference_id].present? ? event_path(@event) : event_path(@event), 'Update'

app/views/supplements/index.html.haml
- title 'Supplemental Documents and Links'

= render partial: 'control_bar'

= render :partial => "supplements/header"
= render :partial => "supplements/supplement", :collection => @supplements

= render :partial => 'shared/pagination', locals: { collection: @supplements }

app/views/supplements/new.html.haml
- title 'Add Supplemental Info'

= render partial: 'control_bar'

.row
  .col-md-12
    %h3
      Add supplemental info to
      = @event.name
    = simple_form_for [@event, @supplement], url: event_supplements_path(@event), :html => {:autocomplete => "off"}  do |f|
      = render :partial => "form_fields", :locals => {:f => f}
      = save_or_cancel f, params[:conference_id].present? ? event_path(@event) : event_path(@event), 'Create'

app/views/supplements/show.html.haml
- content_for :head do
  = tag :link, rel: 'canonical', href: event_supplement_path(@event, @supplement)

= render partial: 'control_bar'

.row
  .col-md-12
    %h3
      Supplemental info for
      = @event.name

.row
  .col-md-12
    %p
      - if @supplement.url.present?
        %b URL
        %br
        = linked_icon_for_supplement(@supplement, link_classes: 'mr-2')
        = @supplement.name
        %br
        %span.fa.fa-fw.mr-2
        = @supplement.url

      - else
        %b Download
        %br
        = linked_icon_for_supplement(@supplement, link_classes: 'mr-2')
        = @supplement.name + '.pdf'
        - if @supplement.file_size.present?
          = "(#{number_to_human_size @supplement.file_size})"
.row
  .col-md-12
    %p
      %b Description
      - if @supplement.description.present?
        = safe_list_sanitizer.sanitize(@supplement.description).try(:html_safe)
      - else
        %i none

- if can?(:edit, @supplement)
  .row
    .col-md-12
      %p
        %b Editor's Notes
        %br
        .card
          .card-body
            = safe_list_sanitizer.sanitize(@supplement.editors_notes).try(:html_safe)

-# There's no social bar here, because only editor can see the Show page
-#.row
-#  .col-md-12
-#    %p= fb_social_bar