config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#news'

  get '/logout',  to: 'user_sessions#destroy', as: :logout
  get '/login',   to: 'user_sessions#new',     as: :login
  get '/about',   to: 'pages#about',           as: :about
  get '/news',    to: 'pages#news',            as: :news
  get '/supporters',   to: 'pages#supporters', as: :supporters
  get '/guidelines',   to: 'pages#guidelines', as: :guidelines
  get '/tips',    to: 'pages#tips',            as: :tips
  get '/contact', to: 'pages#contact',         as: :contact
  get '/robots',  to: 'pages#robots',          as: :robots
  get '/privacy_policy', to: 'pages#privacy_policy', as: :privacy_policy
  get '/terms_of_service', to: 'pages#terms_of_service', as: :terms_of_service

  get '/activate/:id',              to: 'activations#create', as: :activation
  get '/register/:activation_code', to: 'activations#new',    as: :registration
  get 'tags/:tag',                  to: 'presentations#index', as: :tag

  # Provide redirects for legacy conference routes
  get "/conferences",         to: redirect(QueryRedirector.new("/events"))
  get 'conferences/upcoming', to: redirect('/events/upcoming')
  get "/conferences/chart",   to: redirect(QueryRedirector.new("/events/chart"))
  get 'conferences/:slug',    to: redirect('/events/%{slug}')

  namespace :api do
    resources :presentations
    resources :publications
    resources :speakers
  end

  resource  :account
  resources :events do
    collection do
      get :cities_count_by    # the chart data endpoint - returns JSON
      get :chart              # queries the data, renders the chart
      get :upcoming           # for the landing page
    end
    resources :supplements, except: [:index] do
      member do
        get :download
      end
    end
  end
  resources :event_users, only: [:index, :create, :destroy]
  resources :documents do
    member do
      get :download
    end
  end
  resources :languages
  resources :passages
  resources :presentation_publications, only: [:create, :destroy]
  resources :presentation_speakers, only: [:create, :destroy]
  resources :presentations do
    member do
      get :manage_speakers, :manage_publications, :manage_related, :download_handout
    end
    collection do
      get :chart                     # queries the data and pushes it to the chart in an array
      get :tags
    end
  end
  resources :publications do
    collection do
      get :chart                     # queries the data and pushes it to the chart in an array
      get :latest                    # for the landing page
    end
  end
  resources :publishers, except: [:new, :show]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :organizers
  resources :relations, only: [:new, :create, :destroy]
  resources :settings, only: [:index, :show, :edit, :update]
  resources :speakers do
    collection do
      get :presentations_count_by    # the chart data endpoint - returns JSON
      get :chart                     # queries the data and pushes it to the chart in an array
    end
  end
  resources :supplements, only: [:index]    # the supplements dashboard, outside the event context
  resources :users do
    member do
      patch :approve
    end
    collection do
      get   :events
      get   :names
      get   :summary
      get   :supporters
      get   :systat
    end
  end
  resources :user_presentations, only: [:index, :create, :update, :destroy] do
    collection do
      get :most_watched
      get :most_anticipated
      get :notifications
    end
  end
  resources :user_sessions, only: [:new, :create, :destroy]
end

app/models/publication.rb
class Publication < ApplicationRecord

  include SortableNames

  include PublicationsHelper # for unformatting time
  include ApplicationHelper  # for pretty_date()

  has_many    :presentation_publications,   :dependent => :destroy
  has_many    :presentations, through: :presentation_publications

  belongs_to  :creator,   class_name: "User"
  belongs_to  :language

  # Publication doesn't use friendly ID because only editors and admin can see these paths, so they aren't indexed by search engines

  # These are just short word strings and not icons because there aren't good icons for making things like DVD and CD distinct.
  TAPE    = 'Tape'.freeze
  CD      = 'CD'.freeze
  VHS     = 'VHS'.freeze
  DISK    = 'DVD/Blu-ray'.freeze
  LP      = 'Vinyl'.freeze
  CAMPUS  = 'Campus'.freeze
  YOUTUBE = 'YouTube'.freeze      # Is it helpful to make this distinct?
  VIMEO   = 'Vimeo'.freeze        # Is it helpful to make this distinct?  for now, seems like yes
  FACEBOOK = 'FaceBook'.freeze    # Is it helpful to make this distinct?
  INSTAGRAM = 'Instagram'.freeze  # Is it helpful to make this distinct?
  SOUNDCLOUD = 'Soundcloud'.freeze
  PODCAST = 'Podcast'.freeze
  ONLINE  = 'Online'.freeze       # Meant to be an "other" catch-all
  ESTORE  = 'e-Store'.freeze      # This is going away . . . (said Tal in 2018, but it's still there)
  PRINT   = 'Print'.freeze        # Books, pamphlets, Newsletter articles, etc. - physical media
  MOKUJI  = 'Mokuji'.freeze
  FORMATS = [YOUTUBE, CAMPUS, ESTORE, MOKUJI, FACEBOOK, INSTAGRAM, SOUNDCLOUD, VIMEO, PRINT, PODCAST, TAPE, CD, VHS, DISK, LP, ONLINE].freeze  # approximately most to least used

  MINUTES = 'minutes'.freeze
  HMS     = 'hh:mm'.freeze
  TIME_FORMATS = [MINUTES, HMS].freeze

  # Presence of duration isn't validated - but in a few cases, it's just not applicable. When it isn't, we need a way to
  # ensure those don't get flagged by the "heart" query as needing attention because duration is blank.
  HAS_DURATION = [ESTORE, YOUTUBE, CAMPUS, MOKUJI, FACEBOOK, INSTAGRAM, PODCAST, TAPE, CD, VHS, DISK]
  PHYSICAL     = [PRINT, TAPE, CD, VHS, DISK, LP].freeze

  attr_accessor :ui_duration      # duration in hh:mm or hh:mm:ss or raw minutes

  validates :name, :language_id, :speaker_names, presence: true
  validates :format, inclusion: { in: FORMATS, message: "%{value} is not a recognized format" }
  validates :ui_duration, duration_format: true
  validates_numericality_of :duration, greater_than_or_equal_to: 0, allow_blank: true

  before_validation :format_duration, :clean_url

  before_save :update_sortable_name

  # Move the contents of #ui_duration into #duration as raw seconds
  def format_duration
    if ui_duration.present? && ui_duration&.respond_to?(:include?)
      if ui_duration == 'N/A'
        self.duration = nil
        self.ui_duration = ''
      elsif ui_duration.tr('0-9', '').length > 0        # expect there is some delimiter
        delimiter = ui_duration.tr('0-9', '').first     # the typo for colon has to be consistent, 01;18/05 will fail
        ui_duration.gsub!(delimiter, ':')               # whatever the non-digit was, make it a colon
        self.duration =  unformatted_time(ui_duration)  # expect hh:mm or hh:mm:ss format
      else
        self.duration = ui_duration.to_i                # expect raw minutes format
      end
    end
  end

  # Strip off marketing/tracking params and remove video start time params from YouTube and Vimeo
  def clean_url
    return  #   Not yet implemented
  end

  def has_duration?
    HAS_DURATION.include? format
  end

  # For determining which items can be in inventory at all. We're not tracking ARI inventory for things like
  # YouTube, Campus, E-store, etc. which are probably retained at the ARI in some form. Just physical media.
  def physical?
    PHYSICAL.include? format
  end

  def ari_inventory_text
    physical? ? ari_inventory : 'n/a'
  end

  # synthesize a description for FB sharing
  def description
    text = ['A']
    text << [duration, 'minute'] if duration.present?
    text << [format, 'publication']
    text << [ 'from', pretty_date(published_on) ] if published_on.present?
    text << ['by', presentations.first.speaker_names] if presentations.present?
    text.join(' ')
  end

  # Inefficient - use this only for PDF/CSV export. Different from the similarly named helper, which produces HTML
  def event_names
    presentations.map{|p| p.conference_name}.join(', ')
  end

  # Collects the speakers from associated presentations if possible (probably most accurate), otherwise falls back to speaker names
  # Inefficient - use this only for PDF/CSV export.
  def available_speaker_names
    if presentations.present?
      presentations.map{|p| p.speaker_names}.flatten.uniq.join(', ')
    else
      speaker_names
    end
  end

  def language_name
    language&.name
  end

  def language_abbreviation
    language&.abbreviation
  end

  def publication_url
    Rails.application.routes.url_helpers.publication_url(self)
  end

  # The "clean" methods give the contents of rich-text fields with any HTML tags stripped out (for CSV export)
  def clean_description
    ActionView::Base.full_sanitizer.sanitize(description)
  end

  def clean_editors_notes
    ActionView::Base.full_sanitizer.sanitize(editors_notes)
  end

  def clean_details
    ActionView::Base.full_sanitizer.sanitize(details)
  end

  # Hash of human-friendly CSV column names and the methods that get the data for CSV export
  TITLES_AND_METHODS = {
      'Name'              => :name,
      'Event Names'       => :event_names,
      'Speaker Names'     => :available_speaker_names,
      'Published On'      => :published_on,
      'Format'            => :format,
      'Duration'          => :duration,
      'Publisher'         => :publisher,
      'ARI Inventory'     => :ari_inventory_text,  # Shows N/A for non-physical items, which lines up with the UI
      'Notes'             => :notes,               # multi-part info, and details that distinguish one copy from another
      'Media URL'         => :url,
      'Presentation URL'  => :publication_url,
      'Description'       => :clean_description,   # contains a generated one-liner intended for FB meta data
      'Details'           => :clean_details,       # contains supplemental info and references
      'Editors Notes'     => :clean_editors_notes, # references and addresses potential ambiguities and unknowns
  }

  # DocumentWorker uses this to get the header for generated CSV output
  def self.csv_header
    TITLES_AND_METHODS.keys
  end

  def csv_row
    TITLES_AND_METHODS.values.map{|v| self.send(v)}
  end
end

app/controllers/api/publications_controller.rb
module Api
  class PublicationsController < ApiController

    def create
      logger.debug "API publication create"

      # We don't block duplicates here, because publications can have the same name, and we might want to push
      # a publication with a different description when a publication with the same name already exists.

      publication = Publication.create(publication_params.merge(creator_id: current_user.id))

      if publication.errors.empty?
        render :json => { status: "201 created", id: publication.id  }
      else
        render :json => { errors: publication.errors.full_messages }
      end
    end

    private

    def publication_params
      params.require(:publication).permit(:name, :speaker_names, :published_on, :format, :url, :duration, :notes, :editors_notes)
    end

  end
end

app/helpers/publications_helper.rb
module PublicationsHelper

  # Gets an HTML listing of the publications conference names, with canonical ones marked with an icon.
  # The conference name can be plain text, or a link - plain text by default.
  def conference_names(publication, options={})
    linked = options[:linked]
    names = []
    publication.presentation_publications.each do |presentation_publication|
      next unless presentation_publication.presentation.conference_name.present?

      name = ''
      # Start with either a "crown" or indent
      if presentation_publication.canonical
        name += icon('fas', 'crown', :class => 'fa-fw text-warning') + '&nbsp'.html_safe
      else
        name += content_tag(:span, '', class: 'fa fa-fw') + '&nbsp'.html_safe
      end
      # Add the name
      conference = presentation_publication.presentation.conference
      if linked
        # TODO - see whether it's possible to add :sort to sticky_navigation - otherwise it's necessary to reset nav context when switching to conference
        name += link_to truncate(conference.name, length: 80), event_path(conference, nav: 'reset')
      else
        name += truncate(conference.name, length: 80)
      end
      names << name
    end
    ('<br/>' + names.compact.join('<br/>')).html_safe
  end

  def format_and_date(publication)
    if publication.url.present?
      [link_to(icon_for_format(publication)  + ' ' + publication.format, publication.url, target: '_blank'), publication.published_on&.year].compact.join(', ').html_safe
    else
      ["#{ icon_for_format(publication) } #{ publication.format }", publication.published_on&.year].compact.join(', ').html_safe
    end
  end

  # Only the field value itself needs to use this - ordinary show views can use formatted_time()
  def duration_for_display(publication)
    if publication.ui_duration.nil? && !publication.persisted?
      # this is what a create field will get, rather than the normal translation of nil to N/A
      ''
    else
      formatted_time(publication.duration)
    end
  end

  # Converts the duration (integer minutes) into either minutes or hh:mm format, depending on user prefs.
  # For guest users, hh:mm is the default.
  def formatted_time(duration, options={hms: false})
    return 'N/A' if duration.nil? || duration == 0
    seconds = (duration * 60).to_f
    if options[:hms] || defined?(current_user) && current_user&.hms_duration?
      Time.at(seconds).utc.strftime("%H:%M")     # show hh:mm format
    else
      (seconds / 60).round.to_s                  # show raw minutes
    end
  end

  # Converts time in mm or hh:mm format to seconds - simple but not strict format checking
  def unformatted_time(hms)
    return 'n/a' unless hms.include?(':')
    return 'n/a' if hms.count(':') > 2

    # if there is one colon, assume hh:mm - if there are two, assume hh:mm:ss
    factor = hms.count(':') == 2 ? 60.0 : 1.0

    (hms.split(':').reverse.map.with_index{|value, place| value.to_i * 60**place.to_i }.sum / factor).round
  end

  def icon_for_format(publication)
    icon = case publication.format
      # Put the tooltip directly on the icons that are unlikely to have links - TODO - enforce which does and doesn't get a link
    when Publication::TAPE then
      icon('fas', 'tape', 'data-toggle' => "tooltip", title: publication.notes)
    when Publication::CD then
      icon('fas', 'compact-disc', 'data-toggle' => "tooltip", title: publication.notes)
    when Publication::VHS then
      icon('fas', 'ticket-alt', 'data-toggle' => "tooltip", title: publication.notes)
    when Publication::DISK then
      icon('fas', 'compact-disc', 'data-toggle' => "tooltip", title: publication.notes)
    when Publication::LP then
      icon('fas', 'compact-disc', 'data-toggle' => "tooltip", title: publication.notes)
    when Publication::CAMPUS then
      icon('fas', 'university')
    when Publication::YOUTUBE then
      icon('fab', 'youtube')
    when Publication::VIMEO then
      icon('fab', 'vimeo')
    when Publication::FACEBOOK then
      icon('fab', 'facebook')
    when Publication::INSTAGRAM then
      icon('fab', 'instagram')
    when Publication::PODCAST then
      icon('fas', 'podcast')
    when Publication::SOUNDCLOUD then
      icon('fab', 'soundcloud')
    when Publication::ONLINE then
      icon('fas', 'download')
    when Publication::ESTORE then
      icon('fas', 'store')
    when Publication::PRINT then
      icon('fas', 'book')
    when Publication::MOKUJI then
      icon('fas', 'tv')
    else
      icon('fas', 'question-circle')  # This means something was added to Publication FORMATS but not included here
    end
  end

  def linked_icon(publication)
    icon = icon_for_format(publication)
    publication.url.present? ? link_to(icon, publication.url, 'data-toggle' => "tooltip", title: publication.notes, target: '_blank') : icon # individual publications may or may not be links
  end

  # Returns true when the presentation/publication relationship is canonical. Used in the form context when we don't
  # have presentation_publication already.
  def canonical?(presentation, publication)
    return false unless presentation.present?
    return false unless publication.present?

    PresentationPublication.where(presentation_id: presentation.id, publication_id: publication.id).first&.canonical
  end
end

app/views/publications/_automated_candidates.html.haml
%br
  .row
    .col-md-12
      %h4= "Automated Presentation Candidates"
      %ul
        - if @related_presentations.empty?
          %p
            %i Automated searching could not find any candidates
        - @related_presentations.each do |presentation|
          %li
            = link_to presentation.name, presentation_path(presentation), target: '_blank'
            - if presentation.conference_name.present?
              =  "(#{presentation.conference_name})"

            = link_to icon('fas', 'link', :class => 'fa-fw'), "#", onclick: "$('#form_for_#{presentation.id}_#{@publication.id}').submit()", class: "btn btn-sm btn-primary"

            = simple_form_for :presentation_publication, html: { id: "form_for_#{presentation.id}_#{@publication.id}", class: 'form-inline' }, url: presentation_publications_path do |f|
              = f.input :presentation_id, as: :hidden, input_html: { value: presentation.id }
              = f.input :publication_id, as: :hidden, input_html: { value: @publication.id }

app/views/publications/_control_bar.html.haml
- content_for :head do
  = render :partial => "shared/position_search_cursor"

-# This puts the navbar outside the content div so it can span the page
- content_for :body do
  %nav.navbar.navbar-expand-lg.navbar-dark
    .container
      -# To lock the menu open, comment out the button and add .show class to .collapse.navbar-collapse below
      = link_to 'Controls', '#', class: "navbar-brand d-block d-lg-none"
      %button.navbar-toggler{ type: "button", 'data-toggle' => "collapse", 'data-target'=>"#control_bar", 'aria-controls'=>"control_bar", 'aria-expanded'=>"false", 'aria-label'=>"Toggle navigation" }
        %span.navbar-toggler-icon

      .collapse.navbar-collapse#control_bar
        %ul.navbar-nav.mr-auto.d-inline.d-lg-flex
          - if can? :create, Publication
            %li.nav-item{ class: active_if(action_name == 'new', 'mr-1 d-inline-block d-lg-list-item') }
              =link_to icon('fas', 'plus', 'Add', class: 'fa-sm'), new_publication_path, class: 'nav-link', title: 'Add a Publication'

          - if current_user&.editor? || current_user&.admin?
            %li.nav-item{class: active_if(params[:heart].present?, 'mr-1 d-inline-block d-lg-list-item') }
              = link_to icon('fas', 'medkit', class: 'fa-lg fa-fw'), publications_path(search_term: param_context(:search_term), heart: 't'), class: "nav-link", title: 'Needs some work'

          %li.nav-item{class: active_if(params[:sort]&.include?('publications.created_at'), 'mr-1 d-inline-block d-lg-list-item') }
            - if params[:sort]&.include?('publications.created_at')
              = link_to 'Latest', publications_path, class: "nav-link active", title: 'Return to default view'
            - else
              = link_to 'Latest', publications_path(sort: '-publications.created_at', page: 1), class: "nav-link", title: 'Show most recently added first'

          %li.nav-item.dropdown
            = link_to('#', class: active_if(action_name == 'chart', "nav-link dropdown-toggle"), id: "navbarDropdownMenuLink", 'data-toggle' => "dropdown", 'aria-haspopup' => "true", 'aria-expanded' => "false") do
              = icon('fas', 'chart-bar', 'Chart It',   class: 'fa-sm')
            .dropdown-menu{'aria-labelledby' => "navbarDropdownMenuLink"}
              = link_to icon('fas', 'chart-bar', 'by Format',  class: 'fa-sm'), chart_publications_path(chart_type: 'format'), class: "dropdown-item"
              = link_to icon('fas', 'chart-bar', 'by Publisher', class: 'fa-sm'), chart_publications_path(chart_type: 'publisher'), class: "dropdown-item"
              = link_to icon('fas', 'chart-bar', 'by Year',  class: 'fa-sm'), chart_publications_path(chart_type: 'year'), class: "dropdown-item"
              = link_to icon('fas', 'chart-bar', 'Duration by Year', class: 'fa-sm'), chart_publications_path(chart_type: 'duration_year'), class: "dropdown-item"
              =# link_to icon('fas', 'chart-bar', 'Speakers', class: 'fa-sm'), chart_speakers_path(chart_type: 'speaker'), class: "dropdown-item"

          - if can? :create, Publisher
            %li.nav-item{ class: active_if(controller_name == 'publishers', 'mr-1 d-inline-block d-lg-list-item') }
              =link_to 'Publishers', publishers_path, class: 'nav-link', title: 'Manage Publishers'

        -# action-specific buttons or search form
        - if controller_name == 'publications'  # becasuse Publicsher is piggybacking in this space - don't show any of this in that case
          - if action_name == 'show'
            - if can? :destroy, @publication
              = link_to icon('far', 'trash-alt', '', class: 'fa-fw'), publication_path(@publication), :method => :delete, :class => "btn btn-sm btn-danger mr-3", :data => { :confirm => 'Are you sure?' }, :post => true
            - if can? :edit, @publication
              = link_to "Edit", edit_publication_path(@publication), :class => "btn btn-sm btn-primary ml-3"
            = link_to "Done", deduce_done_path, :class => "btn btn-sm btn-secondary ml-3"

          - elsif action_name == 'edit' || action_name == 'update'
            = link_to "Save", "#", class: 'btn btn-sm btn-primary mr-3', onclick: "$('form.edit_publication').submit()"
            = link_to "Cancel", publication_path(@publication), :class => "btn btn-sm btn-secondary ml-3"
          - elsif action_name == 'new' || action_name == 'create'
            = link_to "Create", "#", class: 'btn btn-sm btn-primary mr-3', onclick: "$('form.new_publication').submit()"
            = link_to "Done", publications_path, :class => "btn btn-sm btn-secondary ml-3"
          - else
            = index_search_form

app/views/publications/_publication.html.haml
.row.mb-2
  .col
    = link_to(truncate(publication.name, length: 80, separator: ' '), publication_path(publication))
    = conference_names publication # don't link because it adds clutter, and user can nav there via the presentation
  .col-md-2
    = linked_icon(publication)
    = publication.format
    - if params[:sort]&.include? 'publications.created_at'
      = pretty_date(publication.created_at, style: :year_only, undefined_text: '')
    - else
      = pretty_date(publication.published_on, style: :year_only, undefined_text: '')

  .col-md-1.text-right
    = publication.duration

  .col-md-1.text-right
    = publication.language_abbreviation

  - if params[:heart].present?
    .col-sm-2
      = icon('far', 'clock', class: 'fa-fw') if publication.duration.blank?
      = icon('far', 'calendar-times', class: 'fa-fw') if publication.published_on.blank?
      = icon('fas', 'chalkboard-teacher', class: 'fa-fw') if publication.presentations.blank?

  - if can? :edit, publication
    .col-md-2.text-right
      = link_to icon('far', 'edit', class: 'fa-fw fa-sm'), edit_publication_path(publication), :class => "btn btn-xs btn-primary"
      = link_to icon('far', 'trash-alt', class: 'fa-fw fa-sm'), publication_path(publication), :method => :delete, :class => "btn btn-xs btn-danger", :data => { :confirm => 'Are you sure?' }, :post => true

app/views/publications/duration_by_year_chart.html.haml
= render partial: 'control_bar'

.row.chart-controls
  .col-md-12
    = link_to "Done", publications_path, :class => "btn btn-sm btn-secondary float-right"

    - if param_context(:search_term).present? || param_context(:tag).present?
      = title chart_title_with_context('Publication Duration for')

    - else
      = title "Publication Duration (hours) by Year"

    %p Click a year to see its publications
    #publications_chart
      = render partial: 'shared/publications_chart'
    .text-center Hours

app/views/publications/edit.html.haml
= render partial: 'control_bar'

.row
  .col-md-12
    - if @publication.presentations.blank?
      = title 'Editing Unassociated Publication'
      %h5 Name and Speaker Names may be helpful in finding the presentation later.
    - else
      %h4
        Publication of:
        = @publication.presentations.first.name
        - if @publication.presentations.length > 1
          %br
            %span{ style: 'font-size: small' }
              (multiple presentations map to this publication)

-# The publications form_fields partial does its own column management
= simple_form_for @publication, :html => {:autocomplete => "off"} do |f|
  = render :partial => "form_fields", :locals => {:f => f}
  .row
    .col-md-12
      = save_or_cancel f, publication_path(@publication)

app/views/publications/latest.html.haml
- @publications.each do |publication|
  %p
    %i
      = publication.name
    %br
    = publication.format
    ,
    = pretty_date publication.created_at
    = link_to icon('fas', 'info-circle', class: 'fa-fw'), publication_path(publication)
%p
  = link_to 'more...', publications_path(sort: '-publications.created_at', page: 1)

app/views/publications/new.html.haml
- title 'Add a Publication'

= render partial: 'control_bar'

.row
  .col-md-12
    = simple_form_for @publication, :html => {:autocomplete => "off"} do |f|
      = render :partial => "form_fields", :locals => {:f => f}
      = save_or_cancel f, publications_path, 'Create'

app/views/publications/show.html.haml
- content_for :head do
  = tag :link, rel: 'canonical', href: publication_url(@publication)

= render partial: 'control_bar'

.row
  .col-md-12
    = title "#{ @publication.name }"

.row
  .col-md-12
    %p= safe_list_sanitizer.sanitize(@publication.description).try(:html_safe)

.row
  .col-md-12
    %p= format_and_date(@publication)  # this contains the publication year, if present

    - if @publication.presentations.blank?
      -# This field is just helpful info for hooking up floating publications to presentations
      -# The presentation speakers are authoritative, so once presentation is identified, we hide this.
      %p
        %b Speaker Names
        = @publication.speaker_names

    - if @publication.has_duration?
      %p
        %b Duration
        - if @publication.duration.present?
          = formatted_time @publication.duration
          - unless current_user&.hms_duration?
            mins
        -else
          %i unspecified

    %p
      %b Notes
      - if @publication.notes.present?
        = @publication.notes
      - else
        %i none

.row
  .col-md-12
    %p
      %b Primary language:
      = @publication.language_name

.row
  .col-md-12
    %p
      %b Details
      %br
      - if @publication.details.present?
        = safe_list_sanitizer.sanitize(@publication.details).try(:html_safe)
      - else
        %i none

-# Always show this, even when not-applicable so that it's more clear to the user what's going on
.row
  .col-md-12
    %p
      %b Publisher
      %br
      - if Publication::PHYSICAL.include? @publication.format
        - if @publication.publisher.present?
          = @publication.publisher
        - else
          %i unspecified
      - else
        %i not applicable

-# We're not tracking this for things like YouTube, Campus, E-store, etc. which are probably retained at
-# the ARI in some form, only physical media. FALSE does not mean proven to not have a copy.
- if @publication.physical?
  .row
    .col-md-12
      %p
        %b In ARI Inventory:
        - if Publication::PHYSICAL.include? @publication.format
          - if @publication.ari_inventory
            Yes
          - else
            Haven't found it yet
        - else
          %i not applicable

- if can?(:edit, @publication)
  .row
    .col-md-12
      %p
        %b Editor's Notes
        %br
        .card
          .card-body
            = safe_list_sanitizer.sanitize(@publication.editors_notes).try(:html_safe)

.row
  .col-md-12
    %h4 Associated Presentations
    %ul
      - if @publication.presentation_publications.empty?
        %li
          %i None yet
      - @publication.presentation_publications.each do |presentation_publication|
        %li
          - presentation = presentation_publication.presentation
          = link_to presentation.name, presentation_path(presentation)
          - if presentation.conference.present?
            at
            = link_to presentation.conference_name, event_path(presentation.conference)
          = icon('fas', 'crown', :class => 'fa-fw text-warning') if presentation_publication.canonical
          - if can?(:edit, @publication)
            = link_to icon('far', 'edit', :class => 'fa-fw'), edit_publication_path(@publication, presentation_id: presentation.id)
            = link_to icon('fas', 'unlink', :class => 'fa-fw'), presentation_publication_path(presentation_publication), :method => :delete, :post => true, class: 'text-danger'

-# Let the user find presentations to associate
- if can?(:edit, @publication)
  .row
    .col-md-12
      %h4= "Associate a Presentation"
      = simple_form_for :presentation_publication, url: presentation_publications_path do |f|
        = f.input :publication_id, as: :hidden, input_html: { value: @publication.id }
        = f.input :presentation_id, collection: [['',0]], label: false, input_html: { data: { delimiter: ',', placeholder: "enter a presentation name...", source: presentations_path(format: :json), exclude: @current_presentation_ids }, class: "select2-autocomplete", id: "presentation_picker" }
        .text-right
          = f.submit 'Associate', class: 'btn btn-sm btn-primary'

-# If the controller identified possible related publications, list them for association
=# render :partial => 'automated_candidates'

.row
  .col-md-12
    %p= fb_social_bar