config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#news'

  get '/logout',  to: 'user_sessions#destroy', as: :logout
  get '/login',   to: 'user_sessions#new',     as: :login
  get '/about',   to: 'pages#about',           as: :about
  get '/news',    to: 'pages#news',            as: :news
  get '/supporters',   to: 'pages#supporters', as: :supporters
  get '/guidelines',   to: 'pages#guidelines', as: :guidelines
  get '/tips',    to: 'pages#tips',            as: :tips
  get '/contact', to: 'pages#contact',         as: :contact
  get '/robots',  to: 'pages#robots',          as: :robots
  get '/privacy_policy', to: 'pages#privacy_policy', as: :privacy_policy
  get '/terms_of_service', to: 'pages#terms_of_service', as: :terms_of_service

  get '/activate/:id',              to: 'activations#create', as: :activation
  get '/register/:activation_code', to: 'activations#new',    as: :registration
  get 'tags/:tag',                  to: 'presentations#index', as: :tag

  # Provide redirects for legacy conference routes
  get "/conferences",         to: redirect(QueryRedirector.new("/events"))
  get 'conferences/upcoming', to: redirect('/events/upcoming')
  get "/conferences/chart",   to: redirect(QueryRedirector.new("/events/chart"))
  get 'conferences/:slug',    to: redirect('/events/%{slug}')

  namespace :api do
    resources :presentations
    resources :publications
    resources :speakers
  end

  resource  :account
  resources :events do
    collection do
      get :cities_count_by    # the chart data endpoint - returns JSON
      get :chart              # queries the data, renders the chart
      get :upcoming           # for the landing page
    end
    resources :supplements, except: [:index] do
      member do
        get :download
      end
    end
  end
  resources :event_users, only: [:index, :create, :destroy]
  resources :documents do
    member do
      get :download
    end
  end
  resources :languages
  resources :passages
  resources :presentation_publications, only: [:create, :destroy]
  resources :presentation_speakers, only: [:create, :destroy]
  resources :presentations do
    member do
      get :manage_speakers, :manage_publications, :manage_related, :download_handout
    end
    collection do
      get :chart                     # queries the data and pushes it to the chart in an array
      get :tags
    end
  end
  resources :publications do
    collection do
      get :chart                     # queries the data and pushes it to the chart in an array
      get :latest                    # for the landing page
    end
  end
  resources :publishers, except: [:new, :show]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :organizers
  resources :relations, only: [:new, :create, :destroy]
  resources :settings, only: [:index, :show, :edit, :update]
  resources :speakers do
    collection do
      get :presentations_count_by    # the chart data endpoint - returns JSON
      get :chart                     # queries the data and pushes it to the chart in an array
    end
  end
  resources :supplements, only: [:index]    # the supplements dashboard, outside the event context
  resources :users do
    member do
      patch :approve
    end
    collection do
      get   :events
      get   :names
      get   :summary
      get   :supporters
      get   :systat
    end
  end
  resources :user_presentations, only: [:index, :create, :update, :destroy] do
    collection do
      get :most_watched
      get :most_anticipated
      get :notifications
    end
  end
  resources :user_sessions, only: [:new, :create, :destroy]
end

app/controllers/conferences_controller.rb
class ConferencesController < ApplicationController

  before_action :get_conference, except: [:create, :new, :index, :chart, :upcoming, :cities_count_by]
  before_action :get_organizer_selections, only: [:create, :new, :edit]

  authorize_resource  # friendly_find is incompatible with load_resource

  include ConferencesChart
  include SpeakersChart
  include ConferencesHelper

  def index
    # This handles "My Events" and the ability to list events attended by other users
    if params[:user_id].present?
      @user = User.find(params[:user_id])
      if current_user.id.to_s == params[:user_id] || @user.show_attendance || current_user.admin?
        @conferences = @user.conferences
      else
        @user = nil
        @conferences = Conference
      end
    else
      @conferences = Conference
    end

    @conferences = @conferences.includes(:organizer, :presentations).order('start_date DESC')
    per_page = params[:per] || 10 # autocomplete specifies :per
    # This structure separates out the :q from everything else. It's one or the other, but not both.
    if params[:search_term].present? || params[:heart].present? || params[:event_type].present?
      if params[:event_type].present?
        @conferences = @conferences.where(event_type: params[:event_type])
      end

      if params[:heart].present?
        @conferences = @conferences.where("NOT completed AND conferences.start_date < ?", Date.today)
      end

      if params[:search_term].present?
        term = params[:search_term]
        # State-based search is singled out, because the state abbreviations are short, they match many incidental things.
        # This doesn't work for international states - might be fixed by going to country_state_select at some point.
        if term.length == 2 && States::STATES.map{|term| term[0].downcase}.include?(term.downcase)
          @conferences = @conferences.where('conferences.state = ?', term.upcase)
        else
          @conferences = @conferences.where(base_query, event_type_or_wildcard, "#{term}%", "#{term}%", country_code(term), "#{term}", "#{term}%" )
        end
      end
    elsif params[:q].present?
      # Presentations uses this for picking conference in case where a presentation is created without a conference, then associated later.
      # Returns most recent conferences until the 4 digit year is complete. Year is the only good attribute for ensuring
      # the target conference will show up within a set of 5. Over time, may need to bump the 5 to 6 or 8 - use conferences_by_year
      # chart - value needs to be =< maximum conferences in any one year.
      @conferences = @conferences.where("Extract(year FROM start_date) = ?", params[:q]) if params[:q].present? && params[:q].length == 4
      @conferences = @conferences.limit(7)
    end
    @conferences = @conferences.page(params[:page]).per(per_page)

    # The JSON result for select2 has to be built with the expected keys
    respond_to do |format|
      format.html
      format.json { render json: { total: @conferences.length, users: @conferences.map{|c| {id: c.id, text: c.name } } } }
    end
  end

  # This is a lot like a subset of index, but the layout is quite different, so merging it into one action is tedious.
  # Gets called from jQuery in /news and rendered by jQuery append(html).
  def upcoming
    @conferences = Conference.includes(:organizer).where("conferences.start_date > ?", Date.today).order('start_date ASC')
    render layout: false
  end

  # The charts can snag their data from dedicated endpoints, or pass it directly as data - but the height can't be
  # set when using endpoints, so that method is less suitable for charts that vary by the size of the data set (like
  # a vertical bar chart).
  def chart
    case params[:type]
    when 'cities' then
      @cities = city_count_data.to_a      # build the data here, or pull it from an endpoint in the JS, but not both
      render 'cities_chart'
    when 'countries' then
      @countries = country_count_data.to_a      # build the data here, or pull it from an endpoint in the JS, but not both
      render 'countries_chart'
    when 'years' then
      @years = year_count_data.to_a
      render 'years_chart'
    else
      flash[:error] = 'Unknown chart type'
      redirect_to conferences_path
    end
  end

  # Feeds the frequent cities chart
  def cities_count_by

    respond_to do |format|
      format.html
      format.json { render json: city_count_data.to_json }
    end
  end

  def show
    @conference_user = ConferenceUser.where(conference_id: @conference.id, user_id: current_user&.id).first || ConferenceUser.new
    @presentations = @conference.presentations.order("presentations.sortable_name")
    @user_presentations = current_user.user_presentations if current_user.present?
  end

  def edit
    # Keep custom names - but dynamically change the name based on date/organizer if it's still the default name
    gon.apply_name_default = name_blank_or_default?(@conference)
  end

  def new
    gon.apply_name_default = true
    @conference = Conference.new
  end

  def create
    @conference = Conference.new conference_params
    @conference.city&.strip!
    @conference.state&.strip!
    @conference.creator_id = current_user.id
    if @conference.save
      redirect_to conference_path(@conference)
    else
      flash.now[:error] = 'Your event could not be saved.'
      get_organizer_selections
      logger.debug "Event save failed: #{ @conference.errors.full_messages }"
      render 'new'
    end
  end

  def update
    if @conference.update_attributes conference_params
      redirect_to conference_path(@conference)
    else
      flash.now[:error] = 'Your event could not be saved.'
      get_organizer_selections
      logger.debug "Event save failed: #{ @conference.errors.full_messages }"
      render 'edit'
    end
  end

  def destroy
    if can?(:destroy, @conference) && @conference.presentations.empty?
      @conference.destroy
    else
      flash[:notice] = "That event can't be deleted because it has presentations linked to it."
    end

    redirect_to conferences_path
  end

  private

  def get_conference
    @conference = Conference.friendly.find params[:id]
    redirect_to(@conference, :status => :moved_permanently) and return if params[:id] != @conference.slug
  end

  def get_organizer_selections
    # JS on the conference create page parses the organizer abbreviation out of this
    @organizer_selections = Organizer.all.order(:name).map{|o| ["#{o.name} - #{o.series_name} - #{o.abbreviation}", o.id]}
  end

  def conference_params
    params.require(:conference).permit(
      :name, :event_type, :description, :organizer_id, :registration_url, :program_url, :start_date, :end_date,
      :venue, :venue_url, :city, :state, :country, :completed, :editors_notes
    )
  end
end

app/helpers/conferences_helper.rb
module ConferencesHelper
  # Show a message appropriate for the user's relationship to the conference.
  # Adding presents a button with the new state "I was there"
  # Removing presents a confirmation "You were there" with the trash icon to remove.
  def attendance_status_message(conference)
    if conference.future?
      if current_user.attended? conference
        # This is what the user sees as attendance confirmation, with the trash icon beside it.
        "You are going!"
      else
        # This is what the user sees on the button to confirm attendance
        "I am going!"
      end
    else
      if current_user.attended? conference
        "You were there!"
      else
        "I was there!"
      end
    end
  end

  def chart_title_with_context(intro_text)
    tag  = param_context(:tag).blank? ? nil : content_tag(:i, param_context(:tag))
    term = param_context(:search_term).blank? ? nil : content_tag(:i, param_context(:search_term))
    (intro_text + ' ' + [tag, term].compact.join(" #{ param_context(:operator)} ")).html_safe
  end

  def activated_event_class(event_type, default_class)
    param_context(:event_type) == event_type ? default_class + ' active' : default_class
  end

  def conference_chart_title(pivot)
    if param_context(:user_id).present? && param_context(:user_id) != current_user.id.to_s
      name = User.find(param_context(:user_id))&.name
      title("#{name}'s #{ current_event_type.pluralize } by #{pivot}")
    elsif param_context(:my_events).present?
      title("Your #{ current_event_type.pluralize } by #{pivot}")
    elsif param_context(:search_term).present?
      p = param_context(:search_term).present? ? param_context(:search_term) : nil
      t = param_context(:tag).present? ? param_context(:tag) : nil
      title("#{ current_event_type.pluralize } by #{pivot} For #{ [p, t].compact.join(' and ') }")
    else
      title("#{ current_event_type.pluralize} by #{pivot}")
    end
  end

  # Returns a value that can be passed into ChartKick for height that will generate a reasonable size for all bars
  def bar_chart_height(bar_count)
    "#{bar_count * 25 + 50}px"
  end

  def name_blank_or_default?(conference)
    conference.name.blank? || conference.name == conference.organizer.abbreviation + ' ' + conference.start_date.year.to_s
  end
end

app/views/conferences/_conference.html.haml
%tr{ :class => cycle(:even, :odd) }
  %td
    = link_to(truncate(conference.name, length: 40, separator: ' '), conference_path(conference, nav_params))
    %br
    = conference.date_span
  %td= location_with_non_us_country conference, :short
  %td{ align: 'center' }
    - if conference.program_url.present?
      = link_to icon('far', 'file'), conference.program_url, target: '_blank'
  - if can? :edit, Conference
    %td{ align: 'center' }= icon('fas', 'check', :class => 'fa-lg fa-fw text-success') if conference.completed

  - if can? :edit, conference
    %td{width: 130}
      = link_to icon('far', 'edit', class: 'fa-fw'), edit_conference_path(conference, nav_params), :class => "btn btn-sm btn-primary"
      - if can?(:destroy, conference) && conference.presentations.empty?
        = link_to icon('far', 'trash-alt', class: 'fa-fw'), conference_path(conference), :method => :delete, :class => "btn btn-sm btn-danger", :data => { :confirm => 'Permanently remove this conference?' }, :post => true

app/views/conferences/_control_bar.html.haml
-# This puts the navbar outside the content div so it can span the page
- content_for :body do
  %nav.navbar.navbar-expand-lg.navbar-dark
    .container
      %ul.navbar-nav.mr-auto
        - if can? :create, Conference
          %li.nav-item{ class: action_name == 'new' ? 'active' : ''}
            =link_to icon('fas', 'plus', 'Add', class: 'fa-sm'), new_conference_path, class: 'nav-link', title: 'Add a Conference'

        - if current_user&.editor? || current_user&.admin?
          %li.nav-item{ class: params[:heart].present? ? 'active' : ''}
            = link_to icon('fas', 'medkit', class: 'fa-lg fa-fw').html_safe, conferences_path(search_term: params[:search_term], heart: 't'), class: "nav-link", title: 'Needs some work'

        - if current_user.present?
          %li.nav-item{ class: params[:user_id].present? && params[:user_id] == current_user.id.to_s ? 'active' : ''}
            = link_to "My Events", conferences_path(user_id: current_user.id), class: "nav-link"

        %li.nav-item.dropdown
          = link_to('#', class: "nav-link dropdown-toggle #{action_name == 'chart' ? 'active' : ''}", id: "navbarDropdownMenuLink", 'data-toggle' => "dropdown", 'aria-haspopup' => "true", 'aria-expanded' => "false") do
            = icon('fas', 'chart-bar', 'Chart It',   class: 'fa-sm')
          .dropdown-menu{'aria-labelledby' => "navbarDropdownMenuLink"}
            = link_to icon('fas', 'chart-bar', 'Cities',    class: 'fa-sm'), chart_conferences_path(nav_params.merge(type: 'cities')), class: "dropdown-item"
            = link_to icon('fas', 'chart-bar', 'Countries', class: 'fa-sm'), chart_conferences_path(nav_params.merge(type: 'countries')), class: "dropdown-item"
            = link_to icon('fas', 'chart-bar', 'Years',     class: 'fa-sm'), chart_conferences_path(nav_params.merge(type: 'years')), class: "dropdown-item"

        %li.nav-item.dropdown
          = link_to('#', class: "nav-link dropdown-toggle #{params[:event_type].present? ? 'active' : ''}", id: "navbarDropdownMenuLink", 'data-toggle' => "dropdown", 'aria-haspopup' => "true", 'aria-expanded' => "false") do
            = icon('fas', 'chart-bar', 'Event Type',   class: 'fa-sm')
          .dropdown-menu{'aria-labelledby' => "navbarDropdownMenuLink"}
            = link_to 'Any', conferences_path(nav_params.merge(event_type: nil)), class: "dropdown-item"
            - Conference::EVENT_TYPES.each do |event_type|
              = link_to event_type, conferences_path(nav_params.merge(event_type: event_type)), class: "dropdown-item"

      = index_search_form 'conferences' unless controller_name == 'conference_users' || ['show', 'edit', 'new'].include?(action_name)

      -# action-specific buttons
      - if action_name == 'show'
        - if can?(:destroy, @conference) && @presentations.empty?
          = link_to icon('far', 'trash-alt', '', class: 'fa-fw'), conference_path(@conference), :method => :delete, :class => "btn btn-danger mr-3", :data => { :confirm => 'Permanently remove this conference?' }, :post => true
        - if @conference.future? && @conference.registration_url.present?
          = link_to "Register", @conference.registration_url, :class => "btn btn-primary ml-3", target: '_blank'
        - if can? :create, Presentation
          = link_to "+ Presentation", new_presentation_path(conference_id: @conference.id), :class => "btn btn-primary ml-3"
        - if can? :edit, @conference
          = link_to "Edit", edit_conference_path(@conference, nav_params), :class => "btn btn-primary ml-3"
        = link_to "Done", conferences_path(nav_params), :class => "btn btn-secondary ml-3"

      - if action_name == 'edit'
        = link_to "Cancel", conference_path(@conference), :class => "btn btn-secondary ml-3"
      - elsif action_name == 'new'
        = link_to "Cancel", conferences_path, :class => "btn btn-secondary ml-3"

app/views/conferences/chart.html.haml
.row
  .col-md-12
    = render partial: 'shared/return_from_chart_with_params'

    - if params[:search_term].present?
      %h3
        Conference Cities for
        = params[:search_term]

    - elsif params[:user_id].present?
      %h3
        Your Conference Cities
        = params[:search_term]

    - else
      %h3 Top Conference Cities

    %p Click a city to see its conferences
    #cities_chart
      = render partial: 'shared/cities_chart'
    .text-center Conferences

app/views/conferences/edit.html.haml
- title @conference.name

= render partial: 'control_bar'

- content_for :pre_application_js do
  = Gon::Base.render_data

.row
  .col-md-12
    = simple_form_for @conference do |f|
      = render :partial => "form_fields", :locals => {:f => f}
      = save_or_cancel f, conference_path(@conference, nav_params), 'Save'

app/views/conferences/index.html.haml
- title 'Conferences'

= render partial: 'conferences/control_bar'

- if @user.present?
  .row
    .col-md-12
      %h4
        Events Attended by
        = @user.name

- if @conferences.blank?
  .row
    .col-md-12
      - if @user.present?
        - if @user == current_user
          %p
            You haven't marked any
            = current_event_type.pluralize
            as attended by you.
            - if @user.conferences.empty?
              You can do that on the conference details page. Look for a button that says, "I was there!"
        - else
          %p
            This user hasn't marked any
            = current_event_type.pluralize
            as attended.
      - elsif params[:search_term].present?
        %p No events match the search terms
      - elsif params[:event_type].present?
        %p No events match the event type
      - else
        %p The system doesn't contain any events yet
- else
  .row
    .col-md-12
      %table.table
        = render :partial => "conferences/table_head"
        = render :partial => "conferences/conference", :collection => @conferences

  .row
    .col-md-10
      = paginate @conferences
    .col-md-2
      = per_page_selector conferences_path

app/views/conferences/new.html.haml
- content_for :pre_application_js do
  = Gon::Base.render_data

- title "Add a New Conference"

= render partial: 'control_bar'

.row
  .col-md-12
    = simple_form_for @conference do |f|
      = render :partial => "form_fields", :locals => {:f => f}
      = save_or_cancel f, conferences_path, 'Create'

app/views/conferences/show.html.haml
- title @conference.name

= render partial: 'control_bar'

.row
  .col-md-12
    %h5= @conference.event_type
    %h4
      = @conference.name + ','
      = @conference.date_span
    - if current_user
      .float-right
        - if current_user.attended? @conference
          %p
            = attendance_status_message(@conference)
            = link_to icon('far', 'trash-alt', class: 'fa-fw'), conference_user_path(@conference_user), :method => :delete, :style => "color: #F00", :data => { :confirm => 'Remove your association with this conference?' }, :post => true
        - else
          = simple_form_for @conference_user do |f|
            = f.input :conference_id, as: :hidden, input_html: { value: @conference.id }
            = f.input :user_id, as: :hidden, input_html: { value:current_user.id }
            = f.submit attendance_status_message(@conference)
    %p
      %b Organizer:
      = @conference.organizer&.name
    %p
      %b Venue:
      = location(@conference, :full)
    %p
      %b Program:
      - if @conference.program_url.present?
        = link_to icon('far', 'file', class: 'fa-fw'), @conference.program_url, target: '_blank'
      - else
        %i none
    %p
      %b Description:
      = @conference.description.try(:html_safe)

    - if can? :edit, Conference
      %p
        %b Data entry completed:
        = @conference.completed ? icon('fas', 'check', :class => 'fa-lg fa-fw text-success') : tag.i('not yet')
    %p
      %b Members Attending:
      = @conference.users.length
      - if @conference.users.length > 0 && current_user
        %span.ml-3
          = link_to icon('fas', 'users', class: 'fa-fw'), conference_users_path(conference_id: @conference.id)

- if can?(:edit, @conference) && @conference.editors_notes.present?
  .row
    .col-md-12
      %p
        %b Editor's Notes
        = @conference.editors_notes.try(:html_safe)

.row
  .col-md-12
    %h4 Presentations
    - if @presentations.empty?
      %p None Yet
    - else
      %table.table
        = render :partial => "presentations/table_head"
        = render :partial => "presentations/presentation", :collection =>  @presentations

app/views/conferences/upcoming.html.haml
- @conferences.each do |conference|
  %p
    = conference.name
    %br
    = conference.date_span
    = location_with_non_us_country conference, :short
    = link_to icon('fas', 'info-circle', class: 'fa-fw'), conference_path(conference)