config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#news'

  get '/logout',  to: 'user_sessions#destroy', as: :logout
  get '/login',   to: 'user_sessions#new',     as: :login
  get '/about',   to: 'pages#about',           as: :about
  get '/news',    to: 'pages#news',            as: :news
  get '/supporters',   to: 'pages#supporters', as: :supporters
  get '/guidelines',   to: 'pages#guidelines', as: :guidelines
  get '/tips',    to: 'pages#tips',            as: :tips
  get '/contact', to: 'pages#contact',         as: :contact
  get '/robots',  to: 'pages#robots',          as: :robots
  get '/privacy_policy', to: 'pages#privacy_policy', as: :privacy_policy
  get '/terms_of_service', to: 'pages#terms_of_service', as: :terms_of_service

  get '/activate/:id',              to: 'activations#create', as: :activation
  get '/register/:activation_code', to: 'activations#new',    as: :registration
  get 'tags/:tag',                  to: 'presentations#index', as: :tag

  # Provide redirects for legacy conference routes
  get "/conferences",         to: redirect(QueryRedirector.new("/events"))
  get 'conferences/upcoming', to: redirect('/events/upcoming')
  get "/conferences/chart",   to: redirect(QueryRedirector.new("/events/chart"))
  get 'conferences/:slug',    to: redirect('/events/%{slug}')

  namespace :api do
    resources :presentations
    resources :publications
    resources :speakers
  end

  resource  :account
  resources :events do
    collection do
      get :cities_count_by    # the chart data endpoint - returns JSON
      get :chart              # queries the data, renders the chart
      get :upcoming           # for the landing page
    end
    resources :supplements, except: [:index] do
      member do
        get :download
      end
    end
  end
  resources :event_users, only: [:index, :create, :destroy]
  resources :documents do
    member do
      get :download
    end
  end
  resources :languages
  resources :passages
  resources :presentation_publications, only: [:create, :destroy]
  resources :presentation_speakers, only: [:create, :destroy]
  resources :presentations do
    member do
      get :manage_speakers, :manage_publications, :manage_related, :download_handout
    end
    collection do
      get :chart                     # queries the data and pushes it to the chart in an array
      get :tags
    end
  end
  resources :publications do
    collection do
      get :chart                     # queries the data and pushes it to the chart in an array
      get :latest                    # for the landing page
    end
  end
  resources :publishers, except: [:new, :show]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :organizers
  resources :relations, only: [:new, :create, :destroy]
  resources :settings, only: [:index, :show, :edit, :update]
  resources :speakers do
    collection do
      get :presentations_count_by    # the chart data endpoint - returns JSON
      get :chart                     # queries the data and pushes it to the chart in an array
    end
  end
  resources :supplements, only: [:index]    # the supplements dashboard, outside the event context
  resources :users do
    member do
      patch :approve
    end
    collection do
      get   :events
      get   :names
      get   :summary
      get   :supporters
      get   :systat
    end
  end
  resources :user_presentations, only: [:index, :create, :update, :destroy] do
    collection do
      get :most_watched
      get :most_anticipated
      get :notifications
    end
  end
  resources :user_sessions, only: [:new, :create, :destroy]
end

app/models/passage.rb
class Passage < ApplicationRecord

  belongs_to  :creator,   class_name: "User"

  attr_accessor :update_type

  MAJOR = 'major'
  MINOR = 'minor'
  UPDATE_TYPES = [MINOR, MAJOR] # make minor the first in the drop-down (thus the default)

  # the special entry for the privacy policy - we have to be able to find it
  PRIVACY_POLICY = { name: 'Privacy Policy', assign_var: 'privacy_policy', view: 'pages/privacy_policy' }
  TERMS_OF_SERVICE = { name: 'Terms of Service', assign_var: 'terms_of_service', view: 'pages/terms_of_service' }

  validates :name, :view, :assign_var, :content, :creator_id, presence: true
  validates :update_type,  inclusion: { in: UPDATE_TYPES, message: "%{value} is not a recognized update type", allow_blank: true }     # only present on update

  validates :assign_var, format: { with: /\A[_a-z][_[:alnum:]]*\z/, message: 'must be a legal Ruby variable name', allow_blank: true } # don't double-error message

  validates :name,       uniqueness: true
  validates :assign_var, uniqueness: { scope: :view }

  before_save :set_versions

  def set_versions
    if persisted?
      if update_type == MAJOR
        self.major_version += 1
        self.minor_version = 0
      else
        self.minor_version += 1
      end

    else # set up versions for a brand new passage
      self.major_version = 1
      self.minor_version = 0
    end
  end

  def version
    if persisted?
      "#{major_version}.#{minor_version}"
    else
      "n/a"
    end
  end

  # Don't allow Privacy Policy or Terms of Service to be deleted
  def deletable?
    ![PRIVACY_POLICY[:name], TERMS_OF_SERVICE[:name]].include? name
  end

  # Of all the versioned text entries, the Privacy Policy is a first-class citizen, wired into other models.
  def self.current_privacy_policy_version
    Passage.where(name: PRIVACY_POLICY[:name]).first&.version
  end

  # This gets called at boot time to ensure that the Privacy Policy record exists with the right name.
  def self.ensure_privacy_policy
    return if Rails.env.test?
    begin
      if Passage.where(PRIVACY_POLICY).present?
        logger.debug "Privacy Policy present"
      else
        logger.debug "Creating Privacy Policy base entry"
        passage = create PRIVACY_POLICY.merge(creator: User.find_by_role_id(Role.admin.id), content: "Base Privacy Policy - complete manually")
        logger.error "Error creating base privacy policy: #{ passage.errors.full_messages}" if passage.errors.present?
      end
    rescue Exception => e
      logger.error "Error checking for privacy policy: #{ e }"
    end
  end

  # This gets called at boot time to ensure that the Privacy Policy record exists with the right name.
  def self.ensure_terms_of_service
    return if Rails.env.test?
    begin
      if Passage.where(TERMS_OF_SERVICE).present?
        logger.debug "Terms of Service present"
      else
        logger.debug "Creating Terms of Service base entry"
        passage = create TERMS_OF_SERVICE.merge(creator: User.find_by_role_id(Role.admin.id), content: "Base Terms of Service - complete manually")
        logger.error "Error creating base Terms of Service: #{ passage.errors.full_messages}" if passage.errors.present?
      end
    rescue Exception => e
      logger.error "Error checking for terms of service: #{ e }"
    end
  end
end

app/controllers/passages_controller.rb
class PassagesController < ApplicationController

  before_action :require_admin
  before_action :set_passage, only: [:show, :edit, :update, :destroy]

  def index
    # doesn't participate in sticky_navigation
    @passages = Passage.all.page(params[:page]).per(params[:per])
  end

  def show
  end

  def new
    @passage = Passage.new
  end

  def edit
  end

  def create
    @passage = Passage.new(passage_params)
    @passage.creator_id = current_user.id

    respond_to do |format|
      if @passage.save
        format.html { redirect_to @passage, notice: 'Passage was successfully created.' }
        format.json { render :show, status: :created, location: @passage }
      else
        format.html { render :new }
        format.json { render json: @passage.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @passage.update(passage_params)
        format.html { redirect_to @passage, notice: 'Passage was successfully updated.' }
        format.json { render :show, status: :ok, location: @passage }
      else
        format.html { render :edit }
        format.json { render json: @passage.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @passage.destroy
    respond_to do |format|
      format.html { redirect_to passages_url, notice: 'Passage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_passage
    @passage = Passage.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def passage_params
    params.require(:passage).permit(:name, :view, :assign_var, :content, :minor_version, :major_version, :update_type, :retain_versions )
  end
end

app/views/passages/_control_bar.html.haml
-# This puts the navbar outside the content div so it can span the page
- content_for :body do
  %nav.navbar.navbar-expand-lg.navbar-dark
    .container
      %ul.navbar-nav.mr-auto
        - if can? :create, Passage
          %li.nav-item{ class: action_name == 'new' ? 'active' : ''}
            =link_to icon('fas', 'plus', 'Add', class: 'fa-sm'), new_passage_path, class: 'nav-link', title: 'Add an Organization'

      -# action-specific buttons
      - if action_name == 'show'
        - if can?(:destroy, @passage) && @passage.deletable?
          = link_to icon('far', 'trash-alt', '', class: 'fa-fw'), passage_path(@passage), :method => :delete, :class => "btn btn-sm btn-danger mr-3", :data => { :confirm => 'Are you sure?' }, :post => true
        - if can? :edit, @passage
          = link_to "Edit", edit_passage_path(@passage), :class => "btn btn-sm btn-primary"
        = link_to "Done", passages_path, :class => "btn btn-sm btn-secondary ml-3"

      - elsif action_name == 'edit' || action_name == 'update'
        = link_to "Save", "#", class: 'btn btn-sm btn-primary mr-3', onclick: "$('form.edit_passage').submit()"
        = link_to "Cancel", passage_path(@passage), :class => "btn btn-sm btn-secondary ml-3"
      - elsif action_name == 'new' || action_name == 'create'
        = link_to "Create", "#", class: 'btn btn-sm btn-primary mr-3', onclick: "$('form.new_passage').submit()"
        = link_to "Cancel",  passages_path, :class => "btn btn-sm btn-secondary ml-3"

app/views/passages/_form_fields.html.haml
.form_fields
  = f.input :name, readonly: @passage.persisted?
  = f.input :view, readonly: @passage.persisted?, hint: "The view referencing this content:  controller/view"
  = f.input :assign_var, readonly: @passage.persisted?, label: 'Instance Variable Name', hint: 'must be a legal Ruby variable name'

  - if @passage.persisted?
    = f.input :update_type, as: :select, collection: Passage::UPDATE_TYPES, include_blank: false

  -# Description needs an explicit error treatment because trix_editor isn't integrated with simple_form.
  -# The error CSS is patched in rails_errors_css.scss in order to work with it.
  .form-group{class: "content required string" + (@passage.errors.messages[:content].present? ? " has-error" : "")}
    = f.label :content, class: 'control-label'
    = f.trix_editor :content
    - if @passage.errors.present?
      - @passage.errors.messages[:content].each do |message|
        %span.help-block= message

app/views/passages/_header.html.haml
.row.mb-2
  .col-md-2
    = sorting_header 'Name', :passages_path, 'passages.name'
  .col-md-2.text-right
    Version
  .col
    = sorting_header 'View', :passages_path, 'passages.view'
  .col
    = sorting_header 'Instance Var', :passages_path, 'passages.assign_var'


  - if can? :edit, Passage
    .col-md-3.text-right
      &nbsp;

app/views/passages/_passage.html.haml
.row.mb-2
  .col-md-2= link_to passage.name, passage_path(passage)
  .col-md-2.text-right= passage.version
  .col= passage.view
  .col= passage.assign_var

  - if can? :edit, passage
    .col-md-3.text-right
      = link_to icon('far', 'edit', class: 'fa-fw'), edit_passage_path(passage), :class => "btn btn-xs btn-primary"
      - if can?(:destroy, passage) && passage.deletable?
        = link_to icon('far', 'trash-alt', class: 'fa-fw'), passage_path(passage), :method => :delete, :class => "btn btn-xs btn-danger", :data => { :confirm => 'Are you sure?' }, :post => true

app/views/passages/edit.html.haml
.row
  .col-md-12
    = title "Editing Passage: #{ @passage.name }, version: #{ @passage.version } "

.row
  .col-md-12
    = simple_form_for @passage do |f|
      = render :partial => "form_fields", :locals => {:f => f}
      -# Go back to the concept if that's how we got here - otherwise go back to the passage
      - path_for_cancel = request.referrer.present? && request.referrer.include?('concept') ? concept_path(@passage) : passage_path(@passage)
      = save_or_cancel f, path_for_cancel

app/views/passages/index.html.haml
= title 'Passages'

= render partial: 'control_bar'

- if @passages.blank?
  .row
    .col-md-12
    %p You haven't created any passages yet.

- else
  = render :partial => "header"
  = render :partial => "passage", :collection => @passages

  = render :partial => 'shared/pagination', locals: { collection: @passages }

app/views/passages/new.html.haml
.row
  .col-md-12
    = title "Add Passage"

.row
  .col-md-12
    = simple_form_for @passage do |f|
      = render :partial => "form_fields", :locals => {:f => f}
      = save_or_cancel f, passages_path, 'Create'

app/views/passages/show.html.haml
= render partial: 'control_bar'

- title "Passage #{ @passage.name }"
.row
  .col-md-12
    %h3 Passage
    %p
      Version
      = @passage.version

.row
  .col-md-12
    %p
      %strong Name
      %br
      = @passage.name

.row
  .col-md-12
    %p
      %strong View
      %br
      = @passage.view

.row
  .col-md-12
    %p
      %strong Instance Variable Name
      %br
      = @passage.assign_var

.row
  .col-md-12
    %p
      %strong Content
      %br
      = safe_list_sanitizer.sanitize(@passage.content).try(:html_safe)